### ISSUE TITLE
instructions for starting up

### ISSUE THREAD

**Issue by kay-o** [MelaineGerard/ddev-directus#2]
Hi @MelaineGerard - I agree wholeheartedly with your initiative: great idea to enable Directus projects on DDEV. It's an excellent way to simplify local development.

I've tried a few different ways to start using your project, and each time I get "403 Forbidden - nginx". Unfortunately I've run out of time for digging further for now. Could you provide more of the details you use to start a fresh project?

I've roughed in the following, tho I'm not sure how useful any of it is at this point. If it's on track, please feel free to edit/correct and make it your own:
1. create a directory containing the Directus codebase
    - (option 1) clone the repository
    - (option 2) download an archive of the latest release
2. configure ddev in the project directory
    1. (pre-requisite) install ddev
    2. set project type as `php`
      - (option 1) in Terminal, `ddev config --project-type=php`
      - (option 2) in Terminal, `ddev config` then follow the prompts
3. include this project
    - (option 1) in Terminal, `ddev get MelaineGerard/ddev-directus && ddev restart`
4. add required packages `python3`, `make`, `gcc`, `g++`
    - (option 1) in Terminal, edit ddev config using ``
    - (option 2) in text editor, edit ddev config to add `webimage_extra_packages: [python3, make, gcc, g++]`
5. update `nodejs` to the latest long-term support version
    - (option 1) in text editor, edit ddev config to add `nodejs_version: "20"`
6. enable pnpm
7. set environment variables
8. run the install and build scripts for directus
  1. follow local installation instructions

**Comment by MelaineGerard** [comment]
Hello, I will add it the process in the README

**Comment by MelaineGerard** [comment]
It's now added to the project, feel free to test and confirm that it is good :)

**Comment by MelaineGerard** [comment]
If needed, I can create a simple project with this extension enabled in order to have a demo project.

**Comment by kay-o** [comment]
The instructions successfully produce an html page. Including steps for getting directus running would be useful, if you have the opportunity.

**Comment by kay-o** [comment]
Excellent! thanks for following up again. I'm closing this ticket as 'resolved', and looking forward to using your project as I dig into Directus. Much appreciated!
